### ISSUE TITLE
Create console page with new elements

### ISSUE THREAD

**Issue by StudioSpindle** [semi-technologies/semi-website#159]
*Important note*: This will be a prototype of the console page. It is by no means meant to be used for a 'full' production purpose. 
----
The design can be found here: https://app.zeplin.io/project/5b7e6c6c20f52a2034f91e93/screen/5bb4d2a088ce9e2abaa47d48

**Requirements for the page:**
- It will be populated using simple HTML. _"Most importantly is that I can show something in HTML" - *Bob*_
- It will be a very simple static HTML where a simple REST implementation will take care of the data.

**Tasks:**
- Gather a list of elements that are in the console page
- Build a quick prototype

**Comment by StudioSpindle** [comment]
It will be populated using simple HTML:

**Comment by StudioSpindle** [comment]
New elements:
- select dropdown
- tiles
-- tiles with totals such as  revenue or costs
-- title with graph
- table
-- table has a 'next' and 'previous' option

**Comment by rafaelcanalesduron** [comment]
This is the link to the Zeplin console page: 
https://zpl.io/aMv7kj3 

I sent you an invite to the Zeplin project. You should see it in your email. You have to create an account and log in to access it.
