### ISSUE TITLE
Adjust the search form styling for knowledge page

### ISSUE THREAD

**Issue by StudioSpindle** [semi-technologies/semi-website#185]
The new design shows a placeholder instead of a label. For screenreaders the label is required. (source https://stackoverflow.com/questions/49180218/using-placeholder-instead-of-label)

To accommodate for this the label will have to stay, but can be visually hidden.

**Comment by StudioSpindle** [comment]
Require more info regarding the input field styling. 

@rafaelcanalesduron would it be an idea that we work the forms and input fields out as a component?

This way we can see all the possibile outcomes of the styling. Also removing the grey background may not work: Perhaps we could also research if users will be able to recognize it as being a input (without the grey background).

**Comment by StudioSpindle** [comment]
These are locations where the form/input component is used:

<img width="817" alt="screenshot 2018-11-24 at 13 38 26" src="https://user-images.githubusercontent.com/9882035/48968357-b869da80-efee-11e8-8daf-c703e31c61d8.png">
<img width="850" alt="screenshot 2018-11-24 at 13 38 19" src="https://user-images.githubusercontent.com/9882035/48968358-b869da80-efee-11e8-9c23-95e9811ce59c.png">
<img width="953" alt="screenshot 2018-11-24 at 13 38 01" src="https://user-images.githubusercontent.com/9882035/48968359-b869da80-efee-11e8-8f0b-9d179e8e4d09.png">
<img width="596" alt="screenshot 2018-11-24 at 13 37 52" src="https://user-images.githubusercontent.com/9882035/48968360-b9027100-efee-11e8-83e5-cdd6d5b3d66d.png">

**Comment by StudioSpindle** [comment]
One more thing: Not sure if removing the grey background is working: Perhaps we could also research if users will be able to recognize it as being an input (without this grey background).

**Comment by rafaelcanalesduron** [comment]
@StudioSpindle Should we have a call about this?

> would it be an idea that we work the forms and input fields out as a component?
I'm not exactly sure what you mean with this.
