### ISSUE TITLE
Define share-this requirements

### ISSUE THREAD

**Issue by StudioSpindle** [semi-technologies/semi-website#193]
The design shows share functionality. Any specific requirements or wishes? @bobvanluijt 

Something like this would be an option: https://www.sharethis.com/

**Comment by bobvanluijt** [comment]
For now, we can leave this out IMHO. Or you have a strong opinion on this @rafaelcanalesduron?

**Comment by rafaelcanalesduron** [comment]
It would be nice to add if it's relatively low effort to do so. What Remi suggests seems ok.
What I find important is to try this out as an experiment (if people actually use it) and give us a better idea of how people use the knowledge base and blog.
