### ISSUE TITLE
Build use case / case study pages

### ISSUE THREAD

**Issue by rafaelcanalesduron** [semi-technologies/semi-website#253]
The use case pages need to be build.

**Comment by rafaelcanalesduron** [comment]
@bobvanluijt @carne-vore I have a first proposal of a design for the customer use case pages.

Customer use case overview
https://zpl.io/aXwnXqE 
What aspects of the case studies should we highlight?
- The first three tiles are highlighted cases and make them stand out for the rest. This way the same component can also be used as sections in product pages to lead readers to find out more about the product:
![image](https://user-images.githubusercontent.com/41619961/52488854-16a36400-2bc1-11e9-96bf-ed956717b6fc.png)
- The title of the story should trigger the potential customer in telling them what the value of Weaviate was in that story. 
- There we could also use tags to relate to verticals (retail) or horizontals (e.g. automation) to help people find the right case for them.
- The name of the customer, especially with big brands in certain industries also helps to draw attention and would include them in the tile.
- The 'other cases' are less prominent and would be used once there is a bigger collection of cases.

Customer use case page
https://zpl.io/2G9g13r
Here readers get more details about the story. What aspects should be highlighted in the detailed story?
- On the left there is some background information and a summary. By reading this, people would get the essence of the case.
- In the detailed descriptions we can include different elements such as quotes or images. We could also think of giving all cases the same structure in how the case is presented: for instance intro, process, outcomes.
- At the end of the case there is a call to action. In this case to get in touch.
- We could also include other related stories so people can easily continue exploring.

**Comment by rafaelcanalesduron** [comment]
After our last discussion with @StudioSpindle and @carne-vore, we thought the product icons need more context: better explain the user what they mean.

I added headings to the tags and product icons so it becomes clear what these items mean. 
https://zpl.io/aXwnXqE

**Comment by carne-vore** [comment]
I think the tag was already good and doesn't need to be tagged as a tag... the other one is now good with the redesign - can you remove the TAGS label?
