### ISSUE TITLE
create generic use case 1

### ISSUE THREAD

**Issue by carne-vore** [semi-technologies/semi-website#290]
use case to test look and feel of new use case design - will contain a valid but imaginary use case to illustrate how they will look.

**Comment by carne-vore** [comment]
you will need to look at the feature/use-case branch to review

**Comment by rafaelcanalesduron** [comment]
Hi @bobvanluijt. Answers per question:

1. This is how a use case page should look like:


@bobvanluijt this has all the elements you mentioned, except the partnership logos. If there are logos in the use case, they will be shown in the summary on the left.

Would this format work?

If so, @studiospindle can create the right format for these pages.


2. The 2 different formats are to differentiate use cases which we want to highlight or promote from the rest. This would be useful once we start having more cases.

**Comment by rafaelcanalesduron** [comment]
After a talk with @carne-vore yesterday and Bob's comments I reviewed the current design and have made a few changes. 

On the landing page of use cases, the 'read more use cases' section will be unnecessary for now, so instead let's just use one format for the use cases.
![image](https://user-images.githubusercontent.com/41619961/54029479-d37ce680-41a8-11e9-86f1-e900baf4fa3d.png)
**https://zpl.io/aXwnXqE**

@StudioSpindle there are two things that are missing in that component:
- The tags are not working there, while in the detailed use case page they are.
- The boxes miss the section with products used. Can you add this?

Then for the detailed use case pages I created a mockup using the content that @carne-vore wrote. I added a more prominent image and section with the CTA. Also changed the 'read more' section for the component we use in the use case landing page. 
![image](https://user-images.githubusercontent.com/41619961/54029653-6f0e5700-41a9-11e9-9a20-d9ad36c189e4.png)
https://zpl.io/2v7erWJ

@StudioSpindle could you add these elements to the page and check the layout?
We can go over this on the 18th once you're back.
