### ISSUE TITLE
Add Tableau as a product

### ISSUE THREAD

**Issue by rafaelcanalesduron** [semi-technologies/semi-website#291]
'Tableau' should be added as an add-on product, including its own page.
@bobvanluijt should Tableau become an add-on or a point solution? In your email from 20-Feb you referred to Tableau both as a point solution and an add-on. 
@carne-vore could you start putting content together for this product?
Based on that I can create visuals that would suit this page.

**Comment by bobvanluijt** [comment]
@rafaelcanalesduron add-on.

**Comment by carne-vore** [comment]
@rafaelcanalesduron will you make a tableau logo for the products page and the tableau page

one like the round part of their logo and one like the full logo
![afbeelding](https://user-images.githubusercontent.com/45226724/53494735-b5bfcb00-3a9e-11e9-83e4-b3c6c1939f3a.png)

@StudioSpindle I have made the tableau add on card and it doesn't align like the others but rolls over onto the line below and is extra wide on my local version of this branch (dev). any idea why?

**Comment by carne-vore** [comment]
The pages are ready for graphics and to review the text - I reused the existing semi graphics for the paragraphs of text. If there is more info on how Tableau will be used or integrated (or if I got something wrong) please give to me (I just kept it generic for now)

**Comment by bobvanluijt** [comment]
Wonderful, thanks @carne-vore I'll look at it asap.

**Comment by carne-vore** [comment]
I have contacted Tableau (today by tweet) to ask if we can use their logo in 2 forms - they are apparently careful about how their images are used in public

**Comment by rafaelcanalesduron** [comment]
@carne-vore In what forms do you want to use their logo? If we use corporate identity elements of other businesses we should not alter them. They way it's used now in what you built is great.

**Comment by carne-vore** [comment]
I wanted the circle on its own in some places - I will leave it for now - and maybe they will respond to my tweet asking for permission to use the circle without the name

**Comment by bobvanluijt** [comment]
@dljcollette could you share a screenshot?

**Comment by bobvanluijt** [comment]
@dljcollette did you see this? ⬆️
