### ISSUE TITLE
define visual styling of mobile sticky receipt styling

### ISSUE THREAD

**Issue by StudioSpindle** [semi-technologies/semi-website#313]
Small and medium size have the receipt stick to the bottom

Play with the example here: https://site-nybe7xrg2.now.sh/pricing

Screenshots:

<img width="404" alt="sm_sticky-receipt--opened" src="https://user-images.githubusercontent.com/9882035/54092669-d6b8d380-435c-11e9-8787-d42c4f5da458.png">
<img width="404" alt="sm_sticky-receipt--closed" src="https://user-images.githubusercontent.com/9882035/54092670-d6b8d380-435c-11e9-85f5-18db288e830a.png">
<img width="909" alt=",d_sticky-receipt--closed" src="https://user-images.githubusercontent.com/9882035/54092677-e89a7680-435c-11e9-80be-9964691802d1.png">
<img width="908" alt="md_sticky-receipt--opened png" src="https://user-images.githubusercontent.com/9882035/54092678-e89a7680-435c-11e9-9efc-876bf6d9e61e.png">

**Comment by StudioSpindle** [comment]
Another challenge is the end location of the receipt. When a user is entirely scrolled down on the page, it shouldn't overlap the footer.

At the moment it's under the footer, which is not ideal:

<img width="401" alt="Screenshot 2019-03-10 at 17 50 56" src="https://user-images.githubusercontent.com/9882035/54092701-40d17880-435d-11e9-9d28-cea20b4ae214.png">

Perhaps in a later release, once we have the other receipt (which is also located at the bottom), have . this one dissapear once you are scrolling on that location on the page. That is a bit tricky though...

**Comment by rafaelcanalesduron** [comment]
@StudioSpindle what we can do here is that once you reach the end of the questionnaire when scrolling, the receipt takes the space between the last question and the footer. Would that work?

**Comment by rafaelcanalesduron** [comment]
@StudioSpindle I have a design for the receipt. I have two options: 1) not having a sticky receipt and only showing it at the end of the calculator on mobile, or 2) having the sticky receipt but keep it collapsed and compact and add the behavior described in my [previous comment](https://github.com/SeMI-network/semi-website/issues/313#issuecomment-471468980).

In my opinion it is not necessary to show the price as you fill the form in and the sticky receipt would make the interface more complex. I would like to go for 1), what do you think?

Full screen (option 1)
https://app.zeplin.io/project/5b7e6c6c20f52a2034f91e93/screen/5c87e7caec0dca37fab6b05f

Collapsed (option 2)
https://app.zeplin.io/project/5b7e6c6c20f52a2034f91e93/screen/5c87e7d521064d37f42de40e

Expanded (option 2)
https://app.zeplin.io/project/5b7e6c6c20f52a2034f91e93/screen/5c87e7ccec0dca37fab6b23f

**Comment by StudioSpindle** [comment]
review design by Rafael
