### ISSUE TITLE
supply example image in mobile and desktop version

### ISSUE THREAD

**Issue by StudioSpindle** [semi-technologies/semi-website#318]
Can you supply the example image as a mobile version and a desktop version?

**Comment by StudioSpindle** [comment]
Mobile will be like this by the way. Is this correct? we have the possibility to use a aspect ratio of for example 3:2 (which would be better for social also)

<img width="398" alt="Screenshot 2019-03-12 at 15 59 12" src="https://user-images.githubusercontent.com/9882035/54235713-e1e83c80-44df-11e9-8451-a7bcd3f558a8.png">

**Comment by rafaelcanalesduron** [comment]
@StudioSpindle I added a a mobile version of the page in zeplin. https://zpl.io/2jQgQ0A
The desktop version is also now exportable: 

Question, will this mean that we have to provide two different images for web and desktop?
Is it possible to use only one image for both? And if so as you mention aspect ratio 3:2 might be better for mobile, is it possible to take the same image and crop it in the front end?

**Comment by StudioSpindle** [comment]
@rafaelcanalesduron  Yes, for bandwidth reasons there will be at least two images. It wouldn't make sense forcing the browser to download a 1920*1080 image on mobile with a viewport of 800*600.

I've written a post about this a while ago: http://www.dorel.io/service-manual/global-design-framework/responsive-images.html

As you will see, 3:2 can become quite large on desktop. But that's up to you.
