### ISSUE TITLE
add image to use-case page

### ISSUE THREAD

**Issue by StudioSpindle** [semi-technologies/semi-website#320]

**Comment by StudioSpindle** [comment]
for responsiveness this depends on #318

**Comment by carne-vore** [comment]
@StudioSpindle I threw an image on a use case page and I see a few issues
1 the image comes below the words in the "description:" tag - can you build the image placeholder so it comes above that with tighter spacing like you see in zeplin: https://app.zeplin.io/project/5b7e6c6c20f52a2034f91e93/screen/5c8231bd439ab1bc5add4260

2 "Blog" is the breadcrumb at the top and not "use cases" - is that something I can fix?
3 the width of the sections is nicer on zeplin - can that be styled in in some way?
See image below 
![image](https://user-images.githubusercontent.com/45226724/54604014-04310b80-4a46-11e9-97d8-3a473d956362.png)
