### ISSUE TITLE
use case page needs button "request a demo" 

### ISSUE THREAD

**Issue by carne-vore** [semi-technologies/semi-website#342]
This is currently a header in the template
I think this should be a button like "contact us" but going to a custom "request a demo" page not the standard "contact us" page. 
It could be template-driven and be the same page with smarts to recognise where the request came from
more customer focused than forcing them to  type in "i want a demo of your blah blah"

**Comment by StudioSpindle** [comment]
Has been added: https://github.com/semi-technologies/semi-website/commit/16aa8f4d014de4d2cde20be2061a6b6331ecd6c8#diff-f5a3080d2321b55c7de5905863eca3e3
