### ISSUE TITLE
Pricing calculator - improvements

### ISSUE THREAD

**Issue by carne-vore** [semi-technologies/semi-website#344]
1 Can there be a reset button next to each section so that mistakes can be undone?
2 Can we add a use case tag for each use case so that it is clear which of the 2 main types (MDM, Reporting, Big Data) is the right one - this tag is for the use cases not the calculator - but the link from the use case should prefill the calculator so that as much as possible is done for the user in with 1 click from the use case.
3 Where can I edit the text so that all the drop downs have content?
4 underneath Hosting platform it is not clear that you are done - you need something that says the user is finished and to look at the estimated value on the right

**Comment by StudioSpindle** [comment]
Point 3: That can be done in: `./_data/pricingUseCases.json`. 
Point 4: In a later release it will show you another receipt at the bottom. So that will be added later.

**Comment by StudioSpindle** [comment]
*point 1:* Reset button -> One button for the whole
