### ISSUE TITLE
Validate all urls

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/semi-website#348]
Validate if all URLs function on the website.

**Comment by bobvanluijt** [comment]
@StudioSpindle there is an automated script to validate all URLs. It is in the PR (see above) but will fail because not all links are working.

Feel free to merge if you want to fix it in develop.

**Comment by StudioSpindle** [comment]
Actions: 
error message: 'internally linking to /blog/executive-summary/index, which does not exist ...'
