### ISSUE TITLE
Sitemap is incorrect

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/semi-website#356]
The sitemap.xml contains incorrect urls and urls that don't exsist.

Example:

```xml
<url>
  <loc>
    /http://dev.semi.technology/blog/choose-a-datasource/index
  </loc>
  <lastmod>2019-04-01T18:56:04+00:00</lastmod>
</url>
```

(note the slash before http and the index concatination)

**Comment by StudioSpindle** [comment]
The example URL you're providing is solved with one of the later pushes.

Now it outputs as follows: 
```
...
<url>
<loc>/playbook/style-email.html</loc>
</url>
<url>
<loc>/playbook/style-footer.html</loc>
</url>
<url>
<loc>/playbook/style-forms.html</loc>
</url>
...
```
There is still a problem with this. These are relative URL's and the sitemap should contain absolute URLS.

**Comment by bobvanluijt** [comment]
@StudioSpindle this is solved
