### ISSUE TITLE
Helm instructions reference namespace which is never created

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/semi-website#418]
[These instructions](https://www.semi.technology/documentation/weaviate/current/installation.html#kubernetes) tell helm to install in a `weaviate` namespace, but there is no command beforehand to ever create such a namespace. 

See also https://github.com/semi-technologies/weaviate-helm/issues/13#issuecomment-566656804

**Comment by bobvanluijt** [comment]
Fixed, will be part of the new release.
