### ISSUE TITLE
Update docs to 0.21.12 (from 0.21.6 onwards)

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/semi-website#424]
https://github.com/semi-technologies/weaviate/releases/tag/0.21.6
https://github.com/semi-technologies/weaviate/releases/tag/0.21.7
https://github.com/semi-technologies/weaviate/releases/tag/0.21.8
https://github.com/semi-technologies/weaviate/releases/tag/0.21.9
https://github.com/semi-technologies/weaviate/releases/tag/0.21.10
https://github.com/semi-technologies/weaviate/releases/tag/0.21.11
https://github.com/semi-technologies/weaviate/releases/tag/0.21.12

**Comment by bobvanluijt** [comment]
This already up to date and now obsolete
