### ISSUE TITLE
Draft: When to choose which classification type

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/semi-website#492]
Based on our discussion on Slack here's a draft for a doc article on when to choose which classification type. Note that this is completely raw and unedited, feel free to make changes to fit the general style of the docs:

---

# kNN vs Contextual

Weaviate offers different kinds of classifications. All options can be very powerful if they fit well with the use case. Choosing a classification type which does not fit well with a particular data set can lead to disappointing results. This article helps you choose the best possible classification type for your data set and use case.

## Use case 1: “Categorize Articles”

Imagine you have a dataset comprised of Magazine Articles (sources). You don’t know what each article is about but you know that each article falls into one of three categories (targets): “politics”, “fashion” or “technology”. There are no additional business rules involved and you don’t have any training data. This is a good fit for a “contextual” classification. In such a classification each Article will be analyzed and the most important words will be extracted. These words are then compared - using their vector space distance - to one of the three targets. For example, in an article about “technology” Weaviate has found the words “computer“, “macintosh” and “hardware” to be the most important words. These three words are closer in the vector space to “technology” than they are to “fashion” or “politics”. Weaviate will thus put them in the “technology” category. Each article is treated independently. How many articles have already been categorized into a specific category has no influence on future articles.

This works well when there is a direct relationship between the source item (Article) and the target item (Category). Essentially Weaviate picks the Category it believes to be closest to the Article.

### Summary Use Case
Weaviate chooses target Categories based on how similar a source item is to a potential target item. No training data is required, the performance is independent of the amount of data.

## Use case 2: “Spam or no spam”

Imagine you have a data set of emails. Some of those emails are useful, others are spam. The decision between whether an email is spam follows a set of business rules which you may not know about. For example. it could be likely that if email mentions certain words, such as brand names for specific medication, an email is more likely to be spam. Since we want to use Weaviate for its ML-powers we do not want to work out these business rules manually. Instead we want Weaviate to learn based on the training data we provide it with. Next to our “Email” class (source), we also introduce an “Importance” class of which add three data objects: “Spam”, “Neutral”, “Important”. A contextual classification would yield bad results as an author of a spam email would most likely not use the word “spam” or words close to “spam” in their email. Similarly a regular email would not contain the word “neutral” or similar words. 

This is where a kNN classification becomes very helpful. With “kNN” Weaviate never compares source object to target objects. Instead it compares source objects to similar source objects and “inherits” their labelling. This is why a ‘kNN”-based classification always requires training data. In turn it also improves in quality the more (correctly) labeled data you add. Let’s imagine Weaviate finds an email object with the text “Buy the best stamina drugs for cheap prices at very-questionable-shop.com”, it will now scan the training data set for a close match. Imagine it finds the email with “Buy cheap pills online” and similar emails. Because these pre-labelled objects were marked as spam, Weaviate will make the decision to label the unseen data object as spam as well. The same will happen for “neutral” and “important” emails respectively. 

### Summary Use Case
Weaviate finds similar objects and checks how the were labelled in the past. The more objects added and correctly labeled over time, the better a future classification becomes. Due to this an initial set of training data is required.

### kNN
* requires training data (i.e. pre-labelled data)
* improves with more data
* can support (hidden) business logic
* compares source data points to one another and “inherits” relations

#### contextual
* does not require training data
* quality is independent of the size of the data set, does not improve over time
* does not support business logic
* finds the closest target category match for each source independently

**Comment by etiennedi** [comment]
cc @fefi42 @michaverhagen @laura-ham @bobvanluijt

**Comment by laura-ham** [comment]
Looks good to me

**Comment by bobvanluijt** [comment]
Thanks, I've slightly changed the texts and incorporated them in the website. Will be visible after the new release.
