### ISSUE TITLE
Timestamps 

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/semi-website#503]
The docs state that date accepts ISO 8601 formats. However that standard also allows dates without time or timezone like `2014-05-03`. Weaviate actually requires an [RFC 3339](https://tools.ietf.org/html/rfc3339) formatted date that includes the time and the offset.

https://www.semi.technology/documentation/weaviate/current/add-data/define_schema.html#date-type

**Comment by bobvanluijt** [comment]
Solved
