### ISSUE TITLE
Improve overview of client offerings (CLI/python)

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/semi-website#541]
We have noticed that customers can be confused that "there are two python packages available", i.e. `weaviate` (the python client) and `weaviate-cli` (the repo that builds the CLI). 

On the website the Python client can be found within the regular Weaviate docs:

<img width="188" alt="Screenshot 2020-07-29 at 09 30 25" src="https://user-images.githubusercontent.com/8974479/88770486-33997180-d17e-11ea-8bf5-d6d2abbacca1.png">

The CLI however is displayed prominently on the overview page:

<img width="200" alt="Screenshot 2020-07-29 at 09 31 16" src="https://user-images.githubusercontent.com/8974479/88771133-12855080-d17f-11ea-817b-1ef59356a9eb.png">

## Thoughts
1. This might suggest that the CLI is somehow the preferred method to interact with Weaviate.
1. Maybe we could help the user by creating a "How to interact with Weaviate?" page on which we display all possible solutions with their advantages and disadvantages?
1. The user could see at least four possible ways to interact with Weaviate: (1) REST, (2) GraphQL, (3) CLI, (4) Language libs (Python/Go/Javascript). While combining 1+2 is enough to use all features, users would naturally be drawn to 3+4 which offer a higher level abstraction. However, even when using 3 or 4 the user has to still be aware of at least 2 as GraphQL queries are usually just "forwarded" in the client and 1 alone does not offer the same feature set. How can we simplify this? I don't think 4 ways would be an issue if they all could work stand-alone. But having to combine several ways can become problematic, especially as the user has no easy way of finding out the limitations of a particular method.

**Comment by etiennedi** [comment]
cc @laura-ham @fefi42 @bobvanluijt @michaverhagen

**Comment by bobvanluijt** [comment]
This is being taken care of in the new release of the website
