### ISSUE TITLE
Copying code snippets awkward (macOS/Chrome)

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/semi-website#546]
Trying to copy code snippets from the documentation is very difficult for two reasons:

1. I can't highlight parts of the code as the highlight immediately disappears on mouse-up
1. Even if I try to hit Cmd+C (macOS) while holding the mouse button down, something other than what I highlighted is copied into the clipboard

See the short video clip below to highlight both issues:

[2020-07-30 10-08-42.mp4.zip](https://github.com/semi-technologies/semi-website/files/4999884/2020-07-30.10-08-42.mp4.zip)

**Comment by bobvanluijt** [comment]
Solved in: https://github.com/semi-technologies/semi-website/commit/bed1ec40033d914e39cd17d02127d66bf4c9bc17
